name       : linux-steam-integration
version    : 0.2
homepage   : https://github.com/solus-project/linux-steam-integration
release    : 3
source     :
    - https://github.com/solus-project/linux-steam-integration/releases/download/v0.2/linux-steam-integration-0.2.tar.xz : 7d5a3ee741b348279da1082e38e6ad5de21a213fde4c950df428312d1c4c9fa5
license    : LGPL-2.1
component  : games
summary    : Helper for enabling better Steam integration on Linux
description: |
    A helper shim to enable better Steam* integration on Linux systems. This is part of an effort by Solus to enhance Steam for everyone.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Preload-libxcb-now-with-latest-Steam-runtime.patch
    %reconfigure --enable-frontend --with-real-steam-binary=/usr/lib/steam/steam
build      : |
    %make
install    : |
    %make_install
