name       : linux-steam-integration
version    : '0.5'
homepage   : https://github.com/solus-project/linux-steam-integration
release    : 10
source     :
    - https://github.com/solus-project/linux-steam-integration/releases/download/v0.5/linux-steam-integration-0.5.tar.xz : 77127bbad31ec2c1e4f247bace9c8f916fafa971553d770ec8a5965105cd1caa
license    : LGPL-2.1
component  : games
summary    : Helper for enabling better Steam integration on Linux
description: |
    A helper shim to enable better Steam* integration on Linux systems. This is part of an effort by Solus to enhance Steam for everyone.
builddeps  :
    - pkgconfig(gtk+-3.0)
emul32     : yes
libsplit   : no
patterns   :
    - /usr/lib32  # LSI is required by Steam so you need 32-bit anyway.
setup      : |
    %apply_patches
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # 32-bit build, default to building only libintercept
        %meson_configure -Dwith-shim=none
    else
        # Enable frontend and shim for the 64-bit build
        %meson_configure -Dwith-shim=replacement -Dwith-frontend=true -Dwith-steam-binary=%libdir%/steam/steam
    fi
build      : |
    %meson_build
install    : |
    %meson_install
