name       : linux-steam-integration
version    : 0.7.3
homepage   : https://github.com/getsolus/linux-steam-integration
release    : 38
source     :
    - git|https://github.com/getsolus/linux-steam-integration.git : 66f250db7bf4aa95e7a4fa9e5e2d7b34238eff62
license    : LGPL-2.1-or-later
component  : games
summary    : Helper for enabling better Steam integration on Linux
description: |
    A helper shim to enable better Steam* integration on Linux systems. This is part of an effort by Solus to enhance Steam for everyone.
builddeps  :
    - pkgconfig(gtk+-3.0)
emul32     : yes
libsplit   : no
patterns   :
    - /usr/lib32  # LSI is required by Steam so you need 32-bit anyway.
setup      : |
    COMMONOPTS="-Dwith-libressl-mode=shim -Dwith-new-libcxx-abi=true --buildtype debugoptimized"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # 32-bit build, default to building only libintercept
        %meson_configure -Dwith-shim=none $COMMONOPTS
    else
        # Enable frontend and shim for the 64-bit build
        %meson_configure -Dwith-shim=replacement -Dwith-frontend=true -Dwith-steam-binary=%libdir%/steam/steam $COMMONOPTS
    fi
build      : |
    %ninja_build
install    : |
    %ninja_install
