name       : linux-steam-integration
version    : 0.7.2
homepage   : https://github.com/solus-project/linux-steam-integration
release    : 26
source     :
    - https://github.com/solus-project/linux-steam-integration/releases/download/v0.7.2/linux-steam-integration-0.7.2.tar.xz : 8d7a39b8010a513d8c9a06e6fe5086570df6502fccac3193544b9391992050e7
license    : LGPL-2.1
component  : games
summary    : Helper for enabling better Steam integration on Linux
description: |
    A helper shim to enable better Steam* integration on Linux systems. This is part of an effort by Solus to enhance Steam for everyone.
builddeps  :
    - pkgconfig(gtk+-3.0)
emul32     : yes
libsplit   : no
patterns   :
    - /usr/lib32  # LSI is required by Steam so you need 32-bit anyway.
setup      : |
    COMMONOPTS="-Dwith-libressl-mode=shim -Dwith-libressl-suffix=-libressl"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # 32-bit build, default to building only libintercept
        %meson_configure -Dwith-shim=none $COMMONOPTS
    else
        # Enable frontend and shim for the 64-bit build
        %meson_configure -Dwith-shim=replacement -Dwith-frontend=true -Dwith-steam-binary=%libdir%/steam/steam $COMMONOPTS
    fi
build      : |
    %meson_build
install    : |
    %meson_install
