name       : linux-steam-integration
version    : 0.4.1
homepage   : https://github.com/solus-project/linux-steam-integration
release    : 8
source     :
    - https://github.com/solus-project/linux-steam-integration/releases/download/v0.4.1/linux-steam-integration-0.4.1.tar.xz : c742e3a60a0869408dd11ebe3c878fe66b294e2ca85dd614b8ce3ff20439120c
license    : LGPL-2.1
component  : games
summary    : Helper for enabling better Steam integration on Linux
description: |
    A helper shim to enable better Steam* integration on Linux systems. This is part of an effort by Solus to enhance Steam for everyone.
builddeps  :
    - pkgconfig(gtk+-3.0)
emul32     : yes
libsplit   : no
patterns   :
    - /usr/lib32  # LSI is required by Steam so you need 32-bit anyway.
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # 32-bit build, default to building only libintercept
        %meson_configure -Dwith-shim=none
    else
        # Enable frontend and shim for the 64-bit build
        %meson_configure -Dwith-shim=replacement -Dwith-frontend=true -Dwith-steam-binary=%libdir%/steam/steam
    fi
build      : |
    %meson_build
install    : |
    %meson_install
