name       : linux-steam-integration
version    : 0.1
homepage   : https://github.com/solus-project/linux-steam-integration
release    : 1
source     :
    - https://github.com/solus-project/linux-steam-integration/releases/download/v0.1/linux-steam-integration-0.1.tar.xz : 74822119697c23a2d99adbaf616d0d536e47572c0ea3b1c3fb70b531c6928d39
license    : LGPL-2.1
component  : games
summary    : Helper for enabling better Steam integration on Linux
description: |
    A helper shim to enable better Steam* integration on Linux systems. This is part of an effort by Solus to enhance Steam for everyone.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --enable-frontend --with-real-steam-binary=/usr/lib/steam/steam
build      : |
    %make
install    : |
    %make_install
