name       : linux-steam-integration
version    : 0.3
homepage   : https://github.com/solus-project/linux-steam-integration
release    : 4
source     :
    - https://github.com/solus-project/linux-steam-integration/releases/download/v0.3/linux-steam-integration-0.3.tar.xz : e06b4faee1af4512e8a5af4195b15c21cc596982b9ad9e4a70f5d3db95eee300
license    : LGPL-2.1
component  : games
summary    : Helper for enabling better Steam integration on Linux
description: |
    A helper shim to enable better Steam* integration on Linux systems. This is part of an effort by Solus to enhance Steam for everyone.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --enable-frontend --with-real-steam-binary=/usr/lib/steam/steam
build      : |
    %make
install    : |
    %make_install
